services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: expennies-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.26-alpine
    container_name: expennies-nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: expennies-db
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4306:3306"
